### ISSUE TITLE
[ИДЕЯ][ОФОРМЛЕНИЕ] Граф для веток

### ISSUE THREAD

**Issue by Jrol123** [Jrol123/game_rep#12]
Можно сделать граф с возможными ветками.

Как в различных визуальных новеллах

**Comment by Tyferse** [comment]
Из очевидного.
Разветвление происходит при каждом сделанном выборе. Вершины - выбор, значения (веса) рёбер - выбранный вариант ответа. Можно особым образом обозначить концовки игры.

**Comment by Tyferse** [comment]
Вопрос. Когда мы напишем каким-то образом первую(-ые) ветку(-и) сюжета, нам для большего удобства нужна прога, где мы могли бы визуализировать граф.

**Comment by Jrol123** [comment]
> Вопрос. Когда мы напишем каким-то образом первую(-ые) ветку(-и) сюжета, нам для большего удобства нужна прога, где мы могли бы визуализировать граф.

https://dtf.ru/gamedev/962002-gayd-kak-i-zachem-dekonstruirovat-mehaniki-iz-chuzhih-igr

**Comment by Jrol123** [comment]
Или, к примеру, с помощью draw.io

**Comment by IAmSerepok** [comment]
Сервис под дерево веток [miro.com](https://miro.com/app/dashboard/)
