### ISSUE TITLE
[ИДЕЯ][ВЕТКА] Лже-ветки

### ISSUE THREAD

**Issue by Jrol123** [Jrol123/game_rep#14]
Это идея для создания новой ветки?
- [ ] Нет

Можно сделать лже-ответвления.
К примеру, в #13 за холодильником ничего не будет, а героя *спалят* и ему придётся убегать, или его просто поймают, или это будет просто троллингом

**Comment by Tyferse** [comment]
> Можно сделать лже-ответвления. К примеру, в #13 за холодильником ничего не будет, а героя _спалят_ и ему придётся убегать, или его просто поймают, или это будет просто троллингом

Тогда было бы интереснее добавить скрытый параметр(-ы) который(-ые) мог бы повлиять на появление скрытых веток.

**Comment by Jrol123** [comment]
> > Можно сделать лже-ответвления. К примеру, в #13 за холодильником ничего не будет, а героя _спалят_ и ему придётся убегать, или его просто поймают, или это будет просто троллингом
> 
> Тогда было бы интереснее добавить скрытый параметр(-ы) который(-ые) мог бы повлиять на появление скрытых веток.

Поясни

**Comment by Tyferse** [comment]
> > Тогда было бы интереснее добавить скрытый параметр(-ы) который(-ые) мог бы повлиять на появление скрытых веток.
> 
> Поясни

Если игрок делает определённый выбор или совершает какое-то действие, которое по мнению автора (повествователя, нарратора) является хорошим или плохим, то мы увеличиваем или уменьшаем этот скрытый параметр. При определённых значениях этого скрытого параметра будут доступны или недоступны определённые фичи, диалоговые окна или даже концовки. 
В Undertale есть [параметр fun](https://undertale.fandom.com/wiki/Fun_Value), который в самой игре генерируется рандомно, и от которого зависит появление некоторых событий. ТОлько я бы хотел, чтобы он менялся во время прохождения и не был рандомным.

**Comment by Jrol123** [comment]
Можно!
Вынеси эту идею в отдельную issue

**Comment by Jrol123** [comment]
> > > Тогда было бы интереснее добавить скрытый параметр(-ы) который(-ые) мог бы повлиять на появление скрытых веток.
> > 
> > 
> > Поясни
> 
> Если игрок делает определённый выбор или совершает какое-то действие, которое по мнению автора (повествователя, нарратора) является хорошим или плохим, то мы увеличиваем или уменьшаем этот скрытый параметр. При определённых значениях этого скрытого параметра будут доступны или недоступны определённые фичи, диалоговые окна или даже концовки. В Undertale есть [параметр fun](https://undertale.fandom.com/wiki/Fun_Value), который в самой игре генерируется рандомно, и от которого зависит появление некоторых событий. ТОлько я бы хотел, чтобы он менялся во время прохождения и не был рандомным.

Теперь связана с issue #15
