### ISSUE TITLE
[ИДЕЯ][ВЕТКА] Скрытый параметр, влияющий на внутриигровые события

### ISSUE THREAD

**Issue by Tyferse** [Jrol123/game_rep#15]
### Идея
Добавить скрытый параметр, значения которого будут влиять на "доступ" к некоторым фичам, диалоговым окнам или концовкам.

### Развёрнутое описание
Создаём глобальную переменную (нужно придумать ей название) со значением 0 по умолчанию и в диапазоне от -100 до 100 (к примеру, это можно потом поменять). При совершении определённых выборов или действий игрок будет повышать или понижать значение [этого скрытого параметра]. Как именно он будет изменяться - должно зависеть от мнения автора (повествователя, нарратора), потому что это он управляет игровым пространством, а значит что-то может изменить в зависимости от поведения пользователя.
В дальнейшем, при разработке диалогов, выборов, уровней и прочего нужно будет присвоить изменение [скрытого параметра] большинству возможных (нетривиальных, т. е. не ходьба и не движение мыши, например) действий, которые игрок будет совершать как на определённых уровнях, так и на протяжении всей игры в целом.
Также либо во время, либо после проработки определённого отрезка или уровня игры нужно будет определить, будет ли влиять [cкрытый параметр] на что-либо, и если будет, то на что именно.

**Comment by Jrol123** [comment]
@Tyferse, `help wanted` используется немного в другом случае, поэтому убираю этот тэг

**Comment by Tyferse** [comment]
> @Tyferse, `help wanted` используется немного в другом случае, поэтому убираю этот тэг

Откуда мне знать, когда он используется, а когда нет. Я никогда не создавал issues.

**Comment by RezerdPrime** [comment]
Эта идея уже подразумевает собой постоянный учёт этого параметра, потому наверное проще во время разработки определённого эпизода вносить его.

Типа если ты сделал полноценный уровень, тебе придется рыться в коде, пытаться понять, куда именно пихать параметр и возможно даже переписывать часть кода. Уверен, мы прорабатывать уровни будем долго, потому лучше сразу юзать параметр.

**Comment by Jrol123** [comment]
> Эта идея уже подразумевает собой постоянный учёт этого параметра, потому наверное проще во время разработки определённого эпизода вносить его.
> 
> Типа если ты сделал полноценный уровень, тебе придется рыться в коде, пытаться понять, куда именно пихать параметр и возможно даже переписывать часть кода. Уверен, мы прорабатывать уровни будем долго, потому лучше сразу юзать параметр.

То есть предлагаешь делать этот параметр лишь для определённых веток?
