### ISSUE TITLE
[CORE][ГРАФИКА] Определиться с графическим стилем

### ISSUE THREAD

**Issue by Jrol123** [Jrol123/game_rep#16]
Можно сделать графику как в [Stifled](https://store.steampowered.com/app/514830/Stifled__Echolocation_Horror_Mystery/).
Только без ***размытия***
![idea_1](https://github.com/Jrol123/game_rep/assets/47931983/8bf2b698-4337-45f9-8b9e-a92099e83166)

**Comment by IAmSerepok** [comment]
Графика в несколько уровней aka Evoland?(с общим стилем)
![image](https://github.com/Jrol123/game_rep/assets/132538692/19711fca-ccc7-4916-ad47-202f4bce7268)
![image](https://github.com/Jrol123/game_rep/assets/132538692/255713cc-7a8c-454a-85a5-b9a1c7896575)

**Comment by Tyferse** [comment]
Если игра после пользовательского соглашения начинается с чёрного экрана, то было бы неплохо после появления базовых элементов управления (курсор, возможность делать выбор) сделать первым уровнем классический понг, с которого буквально началась игровая индустрия. А дальше как пойдёт сюжет.
![e90985f5546408d75f902487e56fd](https://github.com/Jrol123/game_rep/assets/115862616/816af0b4-1fe1-46d7-b22e-4fcd54a11346)

**Comment by Tyferse** [comment]
начинать стоит с чёрного экрана, потому что это отсутствие цвета, будто игра не включена, а потом уже начинает появляться что-то стороннее, будто из воздуха, а именно, диалоговое окно со словами нарратора.

**Comment by Jrol123** [comment]
> начинать стоит с чёрного экрана, потому что это отсутствие цвета, будто игра не включена, а потом уже начинает появляться что-то стороннее, будто из воздуха, а именно, диалоговое окно со словами нарратора.

Это относится не к данному issue. Перенеси это в отдельную issue.

**Comment by Jrol123** [comment]
> Графика в несколько уровней aka Evoland?(с общим стилем) ![image](https://user-images.githubusercontent.com/132538692/276031819-19711fca-ccc7-4916-ad47-202f4bce7268.png) ![image](https://user-images.githubusercontent.com/132538692/276031843-255713cc-7a8c-454a-85a5-b9a1c7896575.png)

Предлагаешь не делать "общий стиль"?

Т. е. TD, FPS и т. д. не будут в одном графическом стиле?
Мне кажется это плохое решение.
Лучше сделать один стиль и немного его менять в зависимости от жанра

**Comment by Jrol123** [comment]
> Лучше сделать один стиль и немного его менять в зависимости от жанра
Т. е. основным стилем будет Stifled, но мы можем его немного менять от жанра к жанру

**Comment by IAmSerepok** [comment]
Я же написал, что с сохранением общего стиля

**Comment by IAmSerepok** [comment]
Я предлагаю какой-то простенький(даунгрейднутный) вариант для начала игры и про-up-ываем графику в процессе

**Comment by Jrol123** [comment]
> Я же написал, что с сохранением общего стиля

Просто мне интересно мнение остальных @Tyferse , @RezerdPrime , @Fezwer

**Comment by Jrol123** [comment]
> Я предлагаю какой-то простенький(даунгрейднутный) вариант для начала игры и про-up-ываем графику в процессе

Не уверен, что графику стоит именно up-ать, но видоизменять её нужно.

К тому же, как ты будешь up-ать графику в нелинейной игре?

**Comment by IAmSerepok** [comment]
> > Я предлагаю какой-то простенький(даунгрейднутный) вариант для начала игры и про-up-ываем графику в процессе
> 
> Не уверен, что графику стоит именно up-ать, но видоизменять её нужно.
> 
> К тому же, как ты будешь up-ать графику в нелинейной игре?

Ну дык если по продвижению так или иначе нарратор будет строить собственную "игру" то up-ы графики вполне ложатся

**Comment by IAmSerepok** [comment]
Я же не говорю про прям коренные изменения. Скорее более плавные. Цветов добавить, глубину цвета повысить, объекты по детальнее отрисовывать начать

**Comment by Tyferse** [comment]
> > Я предлагаю какой-то простенький(даунгрейднутный) вариант для начала игры и про-up-ываем графику в процессе
> 
> Не уверен, что графику стоит именно up-ать, но видоизменять её нужно.
> 
> К тому же, как ты будешь up-ать графику в нелинейной игре?

Стоит её улучшать до определённого момента, пока по лору нарратор не остановится на каком-то едином варианте. 

Я бы сказал так: сначала идёт эволюция, в процессе немного меняется палитра цветов, освещение, "пиксельность" (детализация) окружения, а потом, либо в середине веток, либо во второй половине, нарратор приходит к какому-то единому стандарту (может быть даже игрок будет способен повлиять на это, но стоит обсудить отдельно).
