### ISSUE TITLE
[ИДЕЯ][ВЕТКА] Начало игры: ПС

### ISSUE THREAD

**Issue by Tyferse** [Jrol123/game_rep#17]
Продумывание и обыгрывание начала игры как для первого запуска игроком, так и для повторных прохождений (если на это стоит тратить время).

### Это идея для создания полностью новой ветки?
- [x] Да / Нет.

### Более развёрнутое описание.
Любая игра начинается с установки, и для каждой крупной и уважающей себя игры неотъемлемой частью является прочтение и подписание пользовательского соглашения. Так вот, в ***<название игры>*** сам процесс чтения пользовательского соглашения уже является частью игры, нулевой её частью. 

Наша задача - превратить этот элемент в своего рода мини-игру, в конце которой можно получить кнопку "Отклонить" и не согласиться с условиями, прописанными автором (нарратором). Это должно привести к первой по глубине концовке и, соответственно, к первому сделанному выбору в игре.

Текст пользовательского соглашения должен быть по началу максимально шаблонным, но чуть глубже отчасти(!) раскрывать лор (сюжет) игры: цели автора, абстрактные испытания, которые должен будет проходить игрок, их суть (смысл же всего действа следует раскрыть в различных концовках, чтобы сохранить интригу (_очевидно_)).

### Вот некоторые наши задачи:

- [ ] Найти текст шаблона пользовательского соглашения какой-либо игры
- [ ] Отредактировать текст шаблона, вставив в него валидные для лора игры (который тоже нужно будет подробно описать в будущем) термины, имена собственные и мб пасхалки
- [ ] Набросать идеи для "мини-квеста" по поиску пути отказаться от пользовательского соглашения
- [ ] Придумать первую концовку (игрок отклоняет пользовательское соглашение)
- [ ] Решить, что будет с этим этапом игры при повторном прохождении (будут ли она вообще доступна, можно ли будет получить первую концовку снова, и если можно, то что изменится)
- [ ] Чилить до написания основной ветки

**Comment by Tyferse** [comment]
Вот некоторые наши задачи:

- [ ] Найти текст шаблона пользовательского соглашения какой-либо игры
- [ ] Отредактировать текст шаблона, вставив в него валидные для лора игры (который тоже нужно будет подробно описать в будущем) термины, имена собственные и мб пасхалки
- [ ] Набросать идеи для "мини-квеста" по поиску пути отказаться от пользовательского соглашения
- [ ] Придумать первую концовку (игрок отклоняет пользовательское соглашение)
- [ ] Решить, что будет с этим этапом игры при повторном прохождении (будут ли она вообще доступна, можно ли будет получить первую концовку снова, и если можно, то что изменится)
- [ ] Чилить до написания основной ветки

**Comment by RezerdPrime** [comment]
Прежде чем думать над альтернативным вариантом, давайте ещё раз обобщим, что мы накидали по поводу основной ветки сюжета (принятие соглашения). 

У нас типа сразу появляется нарратор и вещает какую-то инфу о том, с чего всё началось, или как?
Даже если он всё равно появляется сразу, после отказа от соглашения нужен хотя бы какой-то переход к дальнейшему взаимодействию нарратора с игроком (пока мы вроде остановились на неком упрашивании дать согласие)

**Comment by Tyferse** [comment]
> У нас типа сразу появляется нарратор и вещает какую-то инфу о том, с чего всё началось, или как? Даже если он всё равно появляется сразу, после отказа от соглашения нужен хотя бы какой-то переход к дальнейшему взаимодействию нарратора с игроком (пока мы вроде остановились на неком упрашивании дать согласие)

Нарратор не должен появляться при чтении пользовательского соглашения, только после.

**Comment by RezerdPrime** [comment]
> > У нас типа сразу появляется нарратор и вещает какую-то инфу о том, с чего всё началось, или как? Даже если он всё равно появляется сразу, после отказа от соглашения нужен хотя бы какой-то переход к дальнейшему взаимодействию нарратора с игроком (пока мы вроде остановились на неком упрашивании дать согласие)
> 
> Нарратор не должен появляться при чтении пользовательского соглашения, только после.

Так я и не говорю, что должен

**Comment by Tyferse** [comment]
> Прежде чем думать над альтернативным вариантом, давайте ещё раз обобщим, что мы накидали по поводу основной ветки сюжета (принятие соглашения).
> 
> У нас типа сразу появляется нарратор и вещает какую-то инфу о том, с чего всё началось, или как?

Да. Без контекста. Вернее, единственный контекст, что будет у игрока - пользовательское соглашение. Сразу после него должно начаться какое-то развитие, сначала медленное, потом ускоряться, и дальше будет понятно по контексту. 

Но нарастание темпа игры, я думаю, будет уместно, когда игрок идёт по альтернативных веткам развития.  В основной же всё должно быть средне-медленным, потому что никаких конфузов не происходит, всё идёт по сценарию (буквально) и все довольны (в особенности нарратор).

**Comment by Jrol123** [comment]
Можно сделать начало как в текстовой адвенчуре.
Или вообще сделать начало *(начальную ветку)* в целом текстовой андвенчурой 
![4d00c6aa0e988943ff8577282ac3887b](https://github.com/Jrol123/game_rep/assets/47931983/b796ac1a-98e9-4e9e-bb95-1f7f4dbed398)

**Comment by Tyferse** [comment]
> Можно сделать начало как в текстовой адвенчуре. Или вообще сделать начало _(начальную ветку)_ в целом текстовой андвенчурой ![4d00c6aa0e988943ff8577282ac3887b](https://user-images.githubusercontent.com/47931983/276824594-b796ac1a-98e9-4e9e-bb95-1f7f4dbed398.png)

Мне кажется, это должно быть третьим по глубине уровненем, либо ложной веткой (которая будет доступна после определённых действий и при определённых значениях <скрытого параметра>).
