### ISSUE TITLE
Базовые графические элементы

### ISSUE THREAD

**Issue by Jrol123** [Jrol123/game_rep#22]
Список задач в порядке уменьшения важности
- [ ] 1. Дизайн пользовательского соглашения
- [ ] 2. Дизайн диалогового окна
- [ ] 3. Варианты курсора
    - [ ] i. Кастомизация (@IAmSerepok, добавь возможные варианты)
- [ ] 4. Примерный дизайн аватарки персонажа
- [ ] 5. Выбрать пиксельный шрифт

ДОП:
- [ ] 1. Графические элементы классических старых игр (Pong, etc. @IAmSerepok, перечисли возможные референсы)

**Comment by Jrol123** [comment]
Разбить на подветки

**Comment by Fezwer** [comment]
Вот вариант пользовательского
![Пользователькое соглашение](https://github.com/Jrol123/game_rep/assets/117802164/f6f7e98e-2c62-4606-86ac-004f4f55e9ff)

**Comment by Fezwer** [comment]
Для дизайна диалогового окна мне нужна какая-нибудь стилистика. Не хочется, что окно слишком скучным выглядело

**Comment by Fezwer** [comment]
Варианты бесплатных пиксельных шрифтов:
https://fonts-online.ru/fonts/frm325x8
https://fonts-online.ru/fonts/better-vcr
https://fonts-online.ru/fonts/minecraft-ten

**Comment by Fezwer** [comment]
@Jrol123 ыыы смотри

**Comment by Jrol123** [comment]
Залил шрифты на Unreal
