### ISSUE TITLE
Отдельный "подвал" для сценаристов

### ISSUE THREAD

**Issue by IAmSerepok** [Jrol123/game_rep#24]
Нужно место, где будут ставиться задачи, проходить обсуждения (и т.д.) по сюжету. Здесь не вариант так как не все моменты вписываются в формат issues, а чат ВК - упаси бог

**Comment by RezerdPrime** [comment]
1) в чем минусы вк?
2) у нас же был тг

**Comment by IAmSerepok** [comment]
Телегу снесли, против миллиона чатов ВК был, в том числе, и ты

**Comment by RezerdPrime** [comment]
> Телегу снесли, против миллиона чатов ВК был, в том числе, и ты

а зачем тг снесли

**Comment by IAmSerepok** [comment]
> > Телегу снесли, против миллиона чатов ВК был, в том числе, и ты
> 
> а зачем тг снесли

"Во имя Царя!"

**Comment by IAmSerepok** [comment]
Очно обсудим, в общем

**Comment by Fezwer** [comment]
ОТКРЫТО
