### ISSUE TITLE
AFK диалоги отображаются некорректно

### ISSUE THREAD

**Issue by IAmSerepok** [Jrol123/game_rep#48]
Из-за того что таймер до следующей фразы начинается по началу рендера текущей, то, если фраза слишком большая, то она не успевает отрисоваться полностью

**Comment by IAmSerepok** [comment]
Из очевидных решений
1. Сделать таймер побольше
    тогда задержка между короткими фразами будет слишком большой
2. Разбить большие предложения на части
    тогда между частями предложения будет задержка
3. Пускать таймер по полной отрисовке текста
   подойдет, но разбираться я в этом сегодня уже не буду

**Comment by Jrol123** [comment]
Просто таймер надо привязать к event on clicked и ставить его заново всякий раз

**Comment by IAmSerepok** [comment]
solved
